#!/usr/bin/env python3
"""
AutoForge Phase 3 Entry Point
Runs full pipeline: Phase 2 code generation + Phase 3 self-healing build loop
"""

import os
import sys
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Add autoforge to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from autoforge.orchestrator import AutoForgeOrchestrator
from autoforge.build import DockerBuilder, StaticAnalyzer, CodeHealer, SelfHealingBuildLoop


def run_full_pipeline(requirement: str, output_dir: str = "autoforge/outputs") -> dict:
    """Run full Phase 2 + Phase 3 pipeline.
    
    Args:
        requirement: User requirement string
        output_dir: Base output directory
        
    Returns:
        Combined results from Phase 2 and Phase 3
    """
    print("="*80)
    print("🚀 AutoForge Phase 3: Full Pipeline")
    print("="*80)
    print(f"Requirement: {requirement}\n")
    
    # Phase 2: Code Generation
    print("📝 PHASE 2: Multi-Agent Code Generation")
    print("-"*80)
    
    orchestrator = AutoForgeOrchestrator()
    phase2_result = orchestrator.run(requirement)
    
    if not phase2_result.get('success'):
        print(f"❌ Phase 2 failed: {phase2_result.get('error', 'Unknown error')}")
        return {
            'phase2': phase2_result,
            'phase3': None,
            'overall_success': False
        }
    
    print(f"✅ Phase 2 completed successfully")
    print(f"Generated service: {phase2_result.get('service_name', 'Unknown')}\n")
    
    # Extract generated code
    service_name = phase2_result.get('service_name', 'UnknownService')
    generated_code = phase2_result.get('final_code', '')
    
    if not generated_code:
        print("❌ No code generated by Phase 2")
        return {
            'phase2': phase2_result,
            'phase3': None,
            'overall_success': False
        }
    
    # Phase 3: Self-Healing Build Loop
    print("🔧 PHASE 3: Self-Healing Build Loop")
    print("-"*80)
    
    # Initialize Phase 3 components
    builder = DockerBuilder()
    analyzer = StaticAnalyzer()
    healer = CodeHealer()
    build_loop = SelfHealingBuildLoop(builder, analyzer, healer, max_attempts=3)
    
    # Create service directory
    service_dir = os.path.join(output_dir, service_name)
    os.makedirs(service_dir, exist_ok=True)
    
    # Run build loop
    phase3_result = build_loop.run(service_dir, service_name, generated_code)
    
    # Determine overall success
    overall_success = phase3_result['final_status'] == 'CERTIFIED'
    
    return {
        'phase2': phase2_result,
        'phase3': phase3_result,
        'overall_success': overall_success,
        'service_name': service_name,
        'service_dir': service_dir
    }


def demo_mode():
    """Run demo with preset tyre pressure requirement."""
    requirement = """
    Create a TyrePressureMonitor service that:
    - Monitors tyre pressure for all four tyres
    - Alerts when pressure is below 30 PSI or above 40 PSI
    - Provides getCurrentPressure() method
    - Provides checkAllTyres() method that returns status
    """
    
    result = run_full_pipeline(requirement)
    
    print("\n" + "="*80)
    print("📊 FINAL RESULTS")
    print("="*80)
    print(f"Phase 2 Success: {result['phase2'].get('success', False)}")
    print(f"Phase 3 Status: {result['phase3']['final_status'] if result['phase3'] else 'N/A'}")
    print(f"Overall Success: {result['overall_success']}")
    
    if result['overall_success']:
        print(f"\n🎉 SUCCESS! Certified code available at:")
        print(f"   {result['service_dir']}/certified/{result['service_name']}.cpp")
    else:
        print(f"\n❌ Pipeline did not complete successfully")
        if result['phase3']:
            print(f"   Check build report: {result['service_dir']}/build_report.json")
    
    print("="*80)


def interactive_mode():
    """Run interactive mode for continuous requirement processing."""
    print("="*80)
    print("🤖 AutoForge Phase 3 - Interactive Mode")
    print("="*80)
    print("Enter requirements (or 'quit' to exit)\n")
    
    while True:
        try:
            requirement = input("Requirement: ").strip()
            
            if requirement.lower() in ['quit', 'exit', 'q']:
                print("Goodbye!")
                break
            
            if not requirement:
                continue
            
            result = run_full_pipeline(requirement)
            
            print(f"\n✅ Pipeline completed - Status: {result['phase3']['final_status'] if result['phase3'] else 'FAILED'}\n")
            
        except KeyboardInterrupt:
            print("\n\nGoodbye!")
            break
        except Exception as e:
            print(f"❌ Error: {e}\n")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        if sys.argv[1] == "--interactive":
            interactive_mode()
        else:
            # Use command line argument as requirement
            requirement = " ".join(sys.argv[1:])
            result = run_full_pipeline(requirement)
            sys.exit(0 if result['overall_success'] else 1)
    else:
        # Default: demo mode
        demo_mode()
